name: Generate and deploy contact log

on:
  push:
    paths:
      - 'data.csv'
      - 'config.json'
      - 'generate_contact_log.py'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate log page
        run: |
          python generate_contact_log.py --csv data.csv --config config.json --output index.html

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'index.html'
          message: 'CI: auto-generate index.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
